version: '3.9'
services:
  # membership:
  #   build: api/.
  #   container_name: membership
  #   ports:
  #     - "5550:5550"
  #   environment: 
  #     BASE_URL : ":5550"
  #     ConnectionString: "membership-db:26257"
  #     DatabaseName: membership
  #     DbUserName: membershipuser
  #     DbPassword: membershippassword
  #   networks:
  #     - membership-network
  #   depends_on:
  #     - membership-db
  membership-db:
    image: postgres:16.2-bullseye
    container_name: membership-db
    hostname: membership-db
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: membershippassword
      POSTGRES_DB: membership
      POSTGRES_USER: membershipuser
      PGDATA: /var/lib/postgresql/data/pgdata
      # COCKROACH_PASSWORD: membershippassword
    networks:
      - membership-network
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - membershipdbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - membership-network      
networks:
  membership-network:
    driver: bridge
volumes:
  membershipdbdata:
