version: '3.9'
services:
  # membership:
  #   build: api/.
  #   container_name: membership
  #   ports:
  #     - "5550:5550"
  #   environment: 
  #     BASE_URL : ":5550"
  #     ConnectionString: "membership-db:26257"
  #     DatabaseName: membership
  #     DbUserName: membershipuser
  #     DbPassword: membershippassword
  #   networks:
  #     - membership-network
  #   depends_on:
  #     - membership-db
  membership-db:
    container_name: crdb
    hostname: crdb
    image: cockroachdb/cockroach:latest
    # command: ["start-single-node", "--cluster-name=example-single-node", "--logtostderr=WARNING", "--log-file-verbosity=WARNING", "--insecure"]
    command: start-single-node
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      - COCKROACH_DATABASE:membership
      - COCKROACH_USER:membershipuser
      - COCKROACH_PASSWORD:membershippassword
    networks:
      - membership-network
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - membershipdbdata:/cockroach/cockroach-data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - membership-network      
networks:
  membership-network:
    driver: bridge
volumes:
  membershipdbdata:
