apiVersion: v1
kind: Service
metadata:
  name: membership-db-service
spec:
  type: NodePort
  selector:
    app: membership-db
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: cockroachdb
      protocol: TCP
      port: 26257
      targetPort: 26257
