apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membership-app
  template:
    metadata:
      labels:
        app: membership-app
    spec:
      containers:
      - name: membership-app
        image: serdarkalayci/membership:0.1.5
        ports:
        - containerPort: 5555
        env:
        - name: DB_PASSWORD
          value: "membershippassword"
        - name: DB_USER
          value: "membershipuser"
        - name: DB_HOST
          value: "192.168.178.91"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "membership"
        - name: BASE_URL
          value: ":5555"
        - name: BASE_PATH
          value: "./"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
